name: Update README with File Count

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Update README
        run: |
          chmod +x update_readme.sh
          bash update_readme.sh

      - name: Commit and push changes !
        run: |
          git config --global user.email "prism9411@gmail.com"
          git config --global user.name "LeeHyungJoo"
          git add update_readme.sh
          git add README.md
          git commit -m "Update file count in README [skip ci]"
          git push
